<?php
$this->mainMenu()->setActiveItemId('overviewcontact');
$this->pageBreadcrumbs()->setLayout('beheer');
$this->pageBreadcrumbs()->setItems([
    'Beheer' => $this->url('beheer'),
    'E-mail' => $this->url('beheer/email'),
    'Add folder' => $this->url('beheer/manageEmailfolders', ['action' => 'addFolder']),
]);
?>
<!-- Page Header -->
<div class="row">
    <h1 class="col">E-MAIL ADD FOLDER</h1>
</div>
<!-- Breadcrumbs -->
<div class="row">
    <div class="col">
        <?= $this->pageBreadcrumbs()->render(); ?>
    </div>
</div>
<div class="row">
    <div class="col-md-auto">
        <form name="addFolder" method="post" action="<?php echo $this->url('beheer/manageEmailfolders', ['action' => 'addFolder']); ?>">
            <div class="form-group">
                <label for="foldername">Foldernaam</label>
                <input type="text" class="form-control" id="foldername" name="foldername" placeholder="foldername">
            </div>
            <div class="form-group">
                <label for="foldername">Bovenliggende folder</label>
                <select name="parentFolder" name="parentfolder" class="form-control">
                    <option value="">--Maak een keuze--</option>
                    <?php foreach ($mailBoxes AS $mailBox) { ?>
                        <?php
                        $mailbox = explode('.', $mailBox['mailbox']);
                        $mailbox = trim(end($mailbox));
                        ?>
                    <option value="<?php echo $mailBox['mailbox']; ?>"><?php echo $mailbox; ?></option>
                    <?php } ?>
                </select>
            </div>
            <button type="submit" class="btn btn-dark">Submit</button>
        </form>
    </div>
</div>