<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4">E-mail add folder</h2>
                </div>
                <div class="row">
                    <div class="col-md-auto">
                        <form name="addFolder" method="post" action="<?php echo $this->url('beheer/manageEmailfolders',
                            ['action' => 'addFolder']); ?>">
                            <div class="form-group mb-2">
                                <label for="foldername">Foldernaam</label>
                                <input type="text" class="form-control" id="foldername" name="foldername"
                                       placeholder="foldername">
                            </div>
                            <div class="form-group mb-2">
                                <label for="foldername">Bovenliggende folder</label>
                                <select name="parentFolder" name="parentfolder" class="form-control">
                                    <option value="">--Maak een keuze--</option>
                                    <?php foreach ($mailBoxes as $mailBox) { ?>
                                        <?php
                                        $mailbox = explode('.', $mailBox['mailbox']);
                                        $mailbox = trim(end($mailbox));
                                        ?>
                                        <option value="<?php echo $mailBox['mailbox']; ?>"><?php echo $mailbox; ?></option>
                                    <?php } ?>
                                </select>
                            </div>
                            <button type="submit" class="btn btn-dark">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>