<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        <div class="col-sm-12 col-md-12 col-xl-12">
            <div class="bg-secondary rounded  p-4">
                <div class="row g-4">
                    <h2 class="col-sm-12 col-md-12 col-xl-12 mb-4">E-mail</h2>
                </div>
                <div class="row">
                    <div class="col-md-auto">
                        <h2>Folders</h2>
                        <div class="list-group table-of-contents">
                            <?php foreach ($mailBoxes as $mailBox) { ?>
                                <a class="list-group-item"
                                   href="<?= $this->url('beheer/email',
                                       ['folder' => $mailBox['mailbox'], 'action' => 'index']); ?>">
                                    <?php
                                    $mailbox = explode('.', $mailBox['mailbox']);
                                    $totalTab = count($mailbox) - 1;
                                    $spaces = '';
                                    if ($totalTab > 0) {
                                        for ($x = 0; $x <= $totalTab; $x++) {
                                            $spaces .= '&nbsp;&nbsp;';
                                        }
                                    }
                                    $mailbox = trim(end($mailbox));
                                    ?>
                                    <?php echo $spaces; ?><span class="glyphicon glyphicon-folder-close"
                                                                aria-hidden="true"></span>&nbsp;<?php echo $mailbox; ?> <?php echo($mailBox['unreadMessages'] > 0 ? '(' . $mailBox['unreadMessages'] . ')' : '') ?>
                                    <span class="glyphicon glyphicon-triangle-right"></span>
                                </a>
                                <?php
                            }
                            ?>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row">
                            <?php
                            $mailboxTitle = explode('.', $mailBoxInfo->Mailbox);
                            $mailboxTitle = end($mailboxTitle);
                            ?>
                            <h2 class="col pull-left"><?php echo $mailboxTitle; ?> (<?php echo $mailBoxInfo->Nmsgs; ?>
                                )</h2>
                        </div>
                        <div class="row">
                            <div id="emailPanel" class="col text-right">
                                <a href="<?= $this->url('beheer/manageEmailfolders', ['action' => 'addFolder']); ?>"
                                   title="Add folder"
                                   class="btn btn-info btn-md">
                                    <img src="/img/icons/folder_add.svg" height="17" class="svg-icon" alt="add folder"/>
                                </a>
                                <a href="<?= $this->url('beheer/email', ['folder' => $folder, 'action' => 'index']); ?>"
                                   title="Refresh folder" class="btn btn-warning btn-md">
                                    <i class="fas fa-sync-alt"></i>
                                </a>
                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#emptyFolderModal">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                                <!-- Button trigger modal -->
                                <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteFolderModal">
                                    <i class="fas fa-times"></i>
                                </button>

                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <!-- Pagination -->
                                <?php echo $this->partial('email/partial/pagination.phtml',
                                    array('pagination' => $pagination, 'folder' => $folder)); ?>

                                <table id="email" class="table table-bordered table-hover table-striped">
                                    <thead class="thead-dark">
                                    <tr>
                                        <th>Onderwerp</th>
                                        <th>Ontvangen op</th>
                                        <th>Verzonden door</th>
                                        <th>Bijlage</th>
                                        <th colspan="2" class="text-center"><i class="fas fa-cogs"></i></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($mails as $mail) { ?>
                                        <tr class="clickEmailRow <?php echo($mail["header"]->Unseen == 'U' ? 'unread' : ''); ?>"
                                            data-id="<?php echo $mail["index"]; ?>"
                                            data-mailbox="<?php echo $folder ?>">
                                            <?php
                                            $dateFromString = strtotime($mail["header"]->date);
                                            $receivedDate = date('d-m-Y H:i:s', $dateFromString);
                                            ?>
                                            <td>
                                                <?php
                                                $subject = '';
                                                foreach (imap_mime_header_decode($mail["header"]->subject) as $subjectPart) {
                                                    $subject .= $subjectPart->text;
                                                }
                                                ?>
                                                <?php echo $subject ?>
                                            </td>
                                            <td><?php echo $receivedDate; ?></td>
                                            <td><?php echo imap_mime_header_decode($mail["header"]->fromaddress)[0]->text; ?></td>
                                            <td class="text-center"><?php echo(isset($mail['structure']->parts[0]) && $mail['structure']->parts[0]->parameters[0]->value != null && strtolower($mail['structure']->parts[0]->parameters[0]->value) != 'utf-8' ? '<span class="glyphicon glyphicon-paperclip" aria-hidden="true"></span>' : '&nbsp;') ?></td>
                                            <td class="text-center">
                                                <a class="btn btn-danger btn-sm" href="
                           <?php echo $this->url('beheer/email', [
                                                    'folder' => $folder,
                                                    'page' => $page,
                                                    'action' => 'deleteEmail',
                                                    'id' => $mail["index"]
                                                ]); ?>">
                                                    <i class="fas fa-trash-alt"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    <?php } ?>
                                    </tbody>
                                </table>
                                <!-- Pagination -->
                                <?php echo $this->partial('email/partial/pagination.phtml',
                                    array('pagination' => $pagination, 'folder' => $folder)); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Confirmation modal delete folder and contents -->
<?php echo $this->partial('email/partial/confirmation-modal-delete-folder.phtml'); ?>

<!-- Confirmation modal delete folder and contents -->
<?php echo $this->partial('email/partial/confirmation-modal-empty-folder.phtml'); ?>