<!-- Confirmation modal delete folder and contents -->
<div class="modal fade" id="emptyFolderModal" tabindex="-1" aria-labelledby="deleteEmailsModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5 text-primary" id="deleteEmailsModalLabel">Delete all e-mails in this folder</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Delete all e-mails in folder?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                <a href="<?= $this->url('beheer/email', ['folder' => $folder, 'action' => 'deleteEmailsInFolder']); ?>" title="Empty folder" class="btn btn-success btn-md">
                    Yes
                </a>
            </div>
        </div>
    </div>
</div>