<!-- Confirmation modal delete folder and contents -->
<div class="modal fade" id="deleteFolderModal" tabindex="-1" aria-labelledby="deleteFolderModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title fs-5 text-primary" id="deleteFolderModalLabel">Delete folder and it's content</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Delete folder and all of it's contents?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">No</button>
                <a href="<?= $this->url('beheer/email', ['folder' => $folder, 'page' => 1, 'action' => 'deleteFolder']); ?>" title="Delete folder" class="btn btn-success btn-md">
                    Yes
                </a>
            </div>
        </div>
    </div>
</div>