<!DOCTYPE html>
<html>
    <head>
        <title>E-mail body</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12">
                    <?= $this->content ?>
                </div>
            </div>
        </div>
    </body>
</html>
